import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import "./globals.css";
import Navbar from "./components/Navbar";
import { ThemeProvider } from "@mui/material/styles";
import { theme } from "./theme/theme";

import ClientLocalizationProvider from "./lib/ClientLocalizationProvider";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Smart Droplets",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <ClientLocalizationProvider>
            <ThemeProvider theme={theme}>
              <div className="flex flex-col h-dvh">
                <Navbar />
                {children}
              </div>
            </ThemeProvider>
          </ClientLocalizationProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}