name: Release

on:
  push:
    branches:
      - release

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Run Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx semantic-release

    - name: Build Docker Image
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker build -t ghcr.io/${{ github.repository }}/nextjs-app:${{ steps.semantic-release.outputs.version }} -t ghcr.io/${{ github.repository }}/nextjs-app:latest .
        docker push ghcr.io/${{ github.repository }}/nextjs-app:${{ steps.semantic-release.outputs.version }}
        docker push ghcr.io/${{ github.repository }}/nextjs-app:latest